#!/bin/bash -e
CMD="docker run"
DOCKER_IMG=binaris
FLAGS="--rm --cap-add=NET_ADMIN -e BINARIS_INVOKE_ENDPOINT \
	   -e BINARIS_DEPLOY_ENDPOINT -e BINARIS_API_KEY -e BINARIS_MOCK_SDK=0"
if [ $# -eq 0 ]; then
	FLAGS="$FLAGS -it"
	RUN_ARG="bash"
else
	RUN_ARG="$@"
fi

$CMD $FLAGS $DOCKER_IMG bash -c "$RUN_ARG"
